learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
        
]

learning_logs/urls.py
"""Define padrões de URL para learning_logs."""

from django.conf.urls import url

from .import views

urlpatterns = [ 
        # Página inicial
        url(r'^$', views.index, name='index'),

        # Mostra todos os assuntos
        url(r'^topics/$', views.topics, name='topics'),

        # Página de detalhes para um único assunto
        url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

        # Página para adicionar um novo assunto
        url(r'^new_topic/$', views.new_topic, name='new_topic'),

        # Página para adicionar uma nova entrada
        url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry,name='new_entry'),

        # Página para editar uma entrada        
        url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
        
]

users/urls.py
"""Define padrões de URL para users"""

from django.conf.urls import url

from django.contrib.auth.views import login

from . import views

urlpatterns = [
    #Página de login
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),

    #Página de cadastro
    url(r'^register/$', views.register, name='register'),
    
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
	"""Um assunto sobre o qual o usuário está aprendendo."""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	# own = models.ForeignKey(User)
	owner = models.ForeignKey(User)


	def __str__(self):
		"""Devolve uma representação em string do modelo."""
		return self.text


class Entry(models.Model):
	"""Algo específico aprendido sobre um assunto."""
	topic = models.ForeignKey(Topic)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'


	def __str__(self):
		"""Devolve uma representação em string do modelo."""
		return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'test': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from .forms import TopicForm, EntryForm

from .models import Topic, Entry
from .forms import TopicForm

def index(request):
    """A página inicial de Learning Log"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Mostra todos os assuntos."""
    # topics = Topic.objects.order_by('date_added')    
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}                                        #X
    return render(request, 'learning_logs/topics.html', context)        #Y 

@login_required
def topic(request, topic_id):
    """Mostra um único assunto e todas as suas entradas."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added') # O sinal "-" antes de date ordena os resultados em ordem inversa
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Adiciona um novo assunto."""
    if request.method != 'POST':
        # Nenhum dado submetido; cria um formulário em branco
        form = TopicForm
    else:
        # Dados de POST submetidos; processa os dados
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)
    

@login_required
def new_entry(request, topic_id):
    """Acrescenta uma nova entrada para um assunto em particular."""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # Nenhum dado submetido; cria um formulário em branco
        form = EntryForm()
    else:
        # Dados de POST submetidos; processa os dados
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}        
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edita uma entrada já existente."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        # Requisição inicial; preenche previamente o formulário com aentrada atual
        form = EntryForm(instance=entry)
    else:
        # Dados de POST submetidos; processa os dados
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            # return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id])) 
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    """Faz logout do usuário."""
    logout(request)
    # return HttpResponseRedirect(reverse('learning_logs:index'))
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
	"""Faz o cadastro de um novo usuário."""
	if request.method != 'POST':
		# Exibe o formulário de cadastro em branco
		form = UserCreationForm()
	else:
		# Processa o formulário preenchido
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			# Faz login do usuario e o redireciona para a pagina inicial
			authenticate_user = authenticate(username=new_user.username,password=request.POST['password1'])
			login(request, authenticate_user)
			return HttpResponseRedirect(reverse('learning_logs:index'))
	context = {'form': form}
	return render(request, 'users/register.html', context)

    

learning_logs/templates/learning_logs/base.html
<p>
<a href="{% url 'learning_logs:index' %}">Learning Log</a> -
<a href="{% url 'learning_logs:topics' %}">Tópicos</a> -
{% if user.is_authenticated %}
  Olá, {{ user.username }}.
  <a href="{% url 'users:logout' %}">log out</a>
{% else %}
  <a href="{% url 'users:register' %}">Cadastro</a>
  <a href="{% url 'users:login' %}">Log in</a>
{% endif %}
  
<a href="{% url 'learning_logs:topics' %}">Tópicos</a>
</p>
{% block content %} {% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Editar entrada ja feita:</p>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="POST">
{% csrf_token %}
{{ form.as_p}}
<button name='Editar'>Salvar edição</button>


</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block content %}

<p>Learning Log ajuda você a manter o aprendizado, para qualquer tipo de assunto que você se interessar.</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    
  <p>Adiciona nova entrada para o tópico:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='Enviar'>Adiciona entrada</button>
  </form>
    
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p> Adiciona um novo Tópico:</p>

  <form action="{% url 'learning_logs:new_topic' %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
   <button name="Enviar">novo tópico</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}
{% block content %}

<p>Topic: {{ topic }}</p>

<p>Entries:</p>
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Adiciona nova entrada</a>

</p>
<ul>
{% for entry in entries %}
    
  <li> 
    <p>{{ entry.date_added|date:'d M , Y H:i' }}</p>
   

    <p>{{ entry.text|linebreaks }}</p>
    <p>
      <a href="{% url 'learning_logs:edit_entry' entry.id %}">Editar entrada</a>

    </p>

  </li>
  {% empty %}
  <li>
      Ainda não há nenhuma entrada para este tópico.
  </li>
{% endfor %}
</ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p>Topics</p>

<ul>
  {% for topic in topics %}  
    <li>
      <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}
    </li>      
  {% empty %}  
  <li>Nenhum tópico foi adiconado por enquanto.</li>
  {% endfor %}  
</ul>
<a href="{% url 'learning_logs:new_topic' %}">Adiconar novo assunto(ou tópico):</a>
{% endblock content %}
  

users/templates/users/login.html
{% extends "learning_logs/base.html" %}

{% block content %}

{% if form.errors %}
<p>Usuáio ou senha incorretos, tente novamente.</p>
{% endif %}

<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name='Enviar'>Entrar</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index'%}" />
</form>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}

{% block content %}

<form method="post" action="{% url 'users:register' %}">
  {% csrf_token %}	
  {{ form.as_p }}

  <button name="Enviar"> Cadastrar </button>
  <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>

</form>

{% endblock content %}